version: '3.9'

services:
  postgres:
    container_name: cats
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=catservice
    ports:
      - "5433:5432"
    restart: unless-stopped